export interface AdvancesCbt {
    id?: number;
    branchId?: number;
    branchCode?:string;
    branchName?:string;
    invoiceBranchId?: number;
    invoiceBranchCode?:string;
    invoiceBranchName?:string;
    dispatchOrderRefNo?: string;
    employeeId?: number;
    employeeFullName?:string;
    refNo?: string;
    refDate?:string;
    advanceGroupId?: number;
    amount?: number;
    currency?: string;
    acceptStep?: number;
    isComplete?: boolean;
    isPayment?: boolean;
    status?: boolean;
    reason?: string;
    feedback?: string;
    notes?: string;
    deleted?: boolean;
    createdBy?: string;
    createdByName?:string;
    createdDate?: Date | string;
    updatedBy?: string;
    updatedDate?: Date | string;
    acceptedBy?: string;
    acceptedByName?:string;
    checked?:boolean;
    has_accept?:boolean;
}
