import { DriverFuelApproval } from "../transports/driver-fuel-approval.model";
import { ExternalOilPurchased } from "../transports/external-oil-purchased.model";
import { AdvancesCbt } from "./advances-cbt.model";
import { DispatchOrderCbtEtc } from "./dispatch-order-cbt-etc.model";
import { DispatchOrderCbtRoutes } from "./dispatch-order-cbt-routes.model";
import { PaymentCbt } from "./payment-cbt.model";

export interface DispatchOrderCbt {
    id?: number;
    branchId?: number;
    customerId?: number;
    customerCode?:string;
    customerName?:string;
    shipmentId?: number;
    jobId?:string;
    refNo?: string;
    vihicleId?: number;
    vihiclelLicensePlates?: string;
    vihicleType?: number;
    vehicleTypeCharge?: number;
    moocId?: number;
    moocLicensePlates?: string;
    driverId?: number;
    driverName?: string;
    driverTel?: string;
    secondDriverId?: number;
    secondDriverName?: string;
    secondDriverTel?: string;
    height?: number;
    volume?: number;
    contType?: string;
    documentNumber?: string;
    referCode?: string;
    fullRoute?: string;
    oilPrice?: number;
    pickupLocationId?:number;
    deliveryLocationId?:number;
    routeId?:number;
    kmQuotaRoute?:number;
    reasons?:string;
    dispatchSummarize?: string;
    departureTime?: Date | string;
    timeTruckArrivesAtLoadingPoint?: Date | string;
    timeTruckDepartsFromLoadingPoint?: Date | string;
    timeTruckPassesThroughBorderGate?: Date | string;
    timeTruckArrivesAtDeliveryPoint?: Date | string;
    timeTruckCompleteDelivery?: Date | string;
    timeTruckReturnToVietnam?: Date | string;
    numberOfHoursPluggedIn?: number;
    startPluggingInTime?: Date | string;
    unpluggingTime?: Date | string;
    note?: string;
    kmQuota?: number;
    oilQuota?: number;
    oilCompensation?: number;
    prevOilSummary?: number;
    oilSummary?: number;
    generatorHours?: number;
    generatorOilQuota?: number;
    startVehicleOdor?: number;
    finishVehicleOdor?: number;
    gradeCs?: number;
    evaluationCs?: string;
    gradeOpMan?: number;
    evaluationOpMan?: string;
    gradeDriver?: number;
    evaluationDriver?: string;
    finished?: boolean;
    noteFinished?: string;
    finishedDate?: Date | string;
    status?: number;
    createdDate?: Date | string;
    createdBy?: string;
    createdByName?:string;
    updatedBy?: string;
    updatedDate?: Date | string;
    acceptedBy?: string;
    acceptedDate?: Date | string;
    closingBy?: string;
    closingDate?: Date | string;
    deleted?: boolean;
    listEtcs?: DispatchOrderCbtEtc[];
    listRoutes?: DispatchOrderCbtRoutes[];
    listPayments?: PaymentCbt[];
    listAdvances?: AdvancesCbt[];
    listFuelApprovals?: DriverFuelApproval[];
    listExternalOilPurchased?: ExternalOilPurchased[];
    checked?:boolean
    totalDriverFuelApproval?:number;
    totalExternalOilPurchased?:number;
    totalMoneyExternalOilPurchased?:number;
    totalPayment?:number;
    totalAdvance?:number;
    totalEtc?:number;
    rStatus?:string;
    feedback?:string;
    tollRouteName?:string;
    purchasePrice?:number;
}
