export class CacheConstants {
    public static ACCOUNT_LIST = 'AccountList';
    public static ADVANCE_GROUP = 'AdvanceGroup';
    public static BRANCH = 'Branch';
    public static CUSTOMER = 'Customer';
    public static CUSTOMER_LOCATIONS = 'CustomerLocations';
    public static CUSTOMER_NORMAL_ROUTES = 'CustomerNormalRoutes';
    public static CUSTOMER_ROUTES = 'CustomerRoutes';
    public static CUSTOMER_TOLL_ROUTES = 'CustomerTollRoutes'; // Not in user list but keep it
    public static DEPARTMENT = 'Department';
    public static DISTRICT = 'District';
    public static EMPLOYEE = 'Employee';
    public static FEE = 'Fee';
    public static GAS_SITE = 'GasSite';
    public static GROUP_FEE = 'GroupFee';
    public static HANDLING_GROUP = 'HandlingGroup';
    public static OPTION_PROCEDURE = 'OptionProcedure';
    public static OTHER_CATEGORIES = 'OtherCategories';
    public static PAYMENT_FEE_GROUP = 'PaymentFeeGroup';
    public static PORTS = 'Ports';
    public static PROVINCE = 'Province';
    public static REVENUE_FEE_GROUP = 'RevenueFeeGroup';
    public static ROUTE = 'Route';
    public static SUPPLIER = 'Supplier';
    public static TICKET_PRICES = 'TicketPrices';
    public static TITLE = 'Title';
    public static TOLL_LOCATIONS = 'TollLocations';
    public static TOLL_ROUTE = 'TollRoute';
    public static TOLL_STATION = 'TollStation';
    public static TRANSIT_PORTS = 'TransitPorts';
    public static TRANSPORT_CATEGORY = 'TransportCategory';
    public static VEHICLE = 'Vehicle';
    public static VEHICLE_OIL_QUOTA = 'VehicleOilQuota';
    public static VEHICLE_TYPE = 'VehicleType'; // Keep existing
}
