export class MessageContstants {
    public static SYSTEM_ERROR_MSG = "Có lỗi kết nối đến máy chủ!";
    public static CONFIRM_DELETE_MSG = "Bạn có chắc muốn xóa bản ghi này?";
    public static CONFIRM_DEBIT0_MSG = "Bạn có chắc muốn len Debit = 0 cho các Job này?";
    public static CONFIRM_LOCKING_MSG = "Bạn có chắc muốn khóa các debit note đã chọn?";
    public static CONFIRM_ACCEPTING_MSG = "Bạn có chắc muốn duyệt các debit note đã chọn?";
    public static CONFIRM_UPDATE_ODOR_MSG = "Bạn có chắc muốn thay đổi số Km của lệnh?";
    public static LOGIN_AGAIN_MSG = "Bạn hết phiên đăng nhập. Mời đăng nhập lại."
    public static CREATED_OK_MSG = "Thêm mới thành công!";
    public static UPDATED_OK_MSG = "Cập nhật thành công!";
    public static ASSIGNING_OK_MSG="Giao việc thành công!";
    public static CANCEL_DISPATCH_ORDER_MSG="Đề nghị dừng lệnh thành công!";
    public static CANCEL_DISPATCH_ORDER_REQUIRED_MSG="Chua nhập lý do hủy lệnh (ghi chú)!";
    public static CANCEL_ASSIGNING_OK_MSG="Hủy giao việc thành công";
    public static CHOOSE_SAME_HANDLINGGROUP="Chỉ được chọn 1 nhóm thực hiện công việc!";
    public static DELETED_OK_MSG = "Xóa thành công!";
    public static LOADD_DATA_OK_MSG = "Tải dữ liệu thành công!";
    public static FORBIDDEN = "Bạn bị chặn truy cập!";
    public static WARNING = "Vui lòng chọn đối tượng cần thao tác.";
    public static NOALLOW = "Bản ghi này không được phép thao tác.";
    public static CREATED_ERR_MSG = "Có lỗi khi thêm mới dữ liệu!";
    public static UPLOAD_ERR_MSG="Có lỗi khi tải đính kèm!";
    public static UPDATED_ERR_MSG = "Có lỗi khi cập nhật dữ liệu!";
    public static DELETE_ERR_MSG = "Có lỗi khi xóa dữ liệu!";
    public static CANNOT_DELETE_DISPATCHORDER="Không được phép xóa Lệnh này!"
    public static DISTANCE_ERR_MSG="Chiều dài cung đường không đúng!";
    public static GETDATA_ERR_MSG = "Có lỗi khi tải dữ liệu!";
    public static GETDATA_OK_MSG = "Tải dữ liệu thành công!";
    public static PROCEDURE_DONE="Tiến trình hoàn thành!";
    public static PROCEDURE_PASS="Bỏ qua tiến trình!";
    public static INPUT_DATA_NOT_VALID="Dữ liệu phí nhập vào chưa chính xác!";
    public static OPMAN_CHANGE_ERR_MSG="Thời gian điều chỉnh không đúng!";
    public static ENDTIME_NOT_LARGER_THAN_STARTTIME="Thời gian hoàn thành phải lớn hơn thời gian bắt đầu!";
    public static FUEL_CLOSING_OK_MSG = "Chốt dầu thành công!";
    public static DATE_TIME_INPUT_NOT_CORRECT="Dữ liệu thời gian không hợp lệ!";
    public static UPDATE_PROCEDURE_ERR_MSG="Một trong các tiến trình trước đó chưa kết thúc, kiểm tra lại!"
    public static ONLEAVE_REQUIED_ERROR="Đang tồn tại phiếu đăng ký phép chưa duyệt, kiểm tra lại!";
    public static EMPLOYEE_DEBIT_CLOSING_REQUIED_ERROR="Đang tồn tại phiếu chốt dư nợ nhân viên chưa duyệt, kiểm tra lại!";
    public static FUEL_CLOSING_REQUIED_ERROR="Đang tồn tại phiếu chốt dầu chưa duyệt, kiểm tra lại!";
    public static FUEL_REQUIED_ERROR="Giá dầu chưa đúng, kiểm tra lại!";
    public static FUEL_QUOTA_ERROR="Định mức dầu chưa đúng, kiểm tra lại!"
    public static IGAS_GET_CODE="Có gửi dữ liệu phiếu cấp dầu ra cây dầu để cấp mã hay không?";
    public static IGAS_TOKEN_EROR="Không lấy được token truy nhập vào iGas, kiểm tra lại!";
    public static CLOSING_FUEL_DRIVER="Chốt dữ liệu dầu hay không?";
    public static TITLE_ERROR_INFO="Thông báo lỗi";
    public static FILE_SIZE_BIGGER ="File không được quá 2MB!"
    public static CHANGED_DRIVER_OK="Thay đổi lái xe thực hiện lệnh thành công!";
    public static CHANGE_DRIVER="Thay đổi lái xe thực hiện lệnh hay không?";
    public static CLOSE_JOB="Bạn muốn khóa lô hàng?";
    public static EMPTY_VALUE ="Không có dữ liệu!"
    public static WORKFLOW_ID_NOT_EXIST="Id Công việc không tồn tại, nhập lại!";
    public static UPDATE_STATE="Cập nhật lại tiến trình hay không?";
    public static LOCKLED_OR_NOT="Khóa phiếu hay không?"
    public static CANCELED_OR_NOT="Hủy phiếu hay không?"
    public static CANCE_SHIPPINGTASK="Hủy công việc hay không?"
    public static UPDATE_DEBIT_INVOICE="Cập nhật thông tin hóa đơn cho các DebitNote đã chọn hay không?"
    public static TITLE_INFO="Thông báo"
    public static APPROVED_SUCCESS = 'Duyệt thành công!'
    public static DENY_SUCCESS = 'Từ chối thành công!'
    public static APPROVE_LENHVC_FCL='Chốt dữ liệu lệnh vận chuyển FCL?'
    public static PORT_REQUIRED_ERROR="Thông tin trung chuyển cảng, bãi chưa đúng, kiểm tra lại!"
    public static UPDATE_ACCOUNTING_DATE="Cập nhật ngày vận hành mới hay không?"
    public static TAXCODE_EXIST="Mã số thuế đã tồn tại, kiểm tra lại!"
    public static DUPLICATE_SHIPPINGTASK="Nhân công việc vận tải này hay không?"
    public static DUPLICATE_SHIPPINGTASK_SUCCESS="Nhân công việc vận tải thành công?"
    public static CONFIRM_ACCEPT_TRAINING_MSG="Duyệt Bước 2 tài liệu đào tạo hay không?"
    public static CONFIRM_RECEIVING_TRAINING_MSG="Bạn bắt đầu sửa tài liệu này đúng không?"
    public static CONFIRM_MODIFIED_TRAINING_MSG="Bổ sung, sửa đổi tài liệu đào tạo này hay không?"
    public static CONFIRM_ACCEPT_GARAGE_ACCOUNT="Duyệt cấp tài khoản này hay không?"
}
