import { CustomerLocations } from "./danhmuc/customer-locations.model";
import { CustomerNormalRoutes } from "./danhmuc/customer-normal-routes.model";
import { CustomerRoutes } from "./danhmuc/customer-routes.model";
import { CustomerTollRoutes } from "./danhmuc/customer-toll-routes";

export interface Customer {
  id?: number;
  customerName?: string;
  nameEnglish?: string;
  customerCode?: string;
  provinceCode?: string;
  districtCode?: string;
  industrialZoneId?: number ;
  address?: string;
  taxCode?: string;
  tel?: string;
  fax?: string;
  website?: string;
  countryCode?: string;
  bankAccountNumber?: string;
  bankName?: string;
  contact?: string;
  contactPosition?: string;
  contactTel?: string;
  contactEmail?: string;
  employeeId?: number ;
  branchId?: number ;
  invoiceIssuingBranchId?:number;
  parentId?: number ;
  notes?: string;
  latitude?: number ;
  longitude?: number ;
  status?:boolean;
  checked?: boolean;
  abbName?:string;
  reason?:string;
  isDeny?:boolean;
  listFee?:string;
  teamId?:number;
  teamName?:string;
  locked?:boolean;
  thirdPartyInvoice?:string;
  informationOfSurchargeInvoice?:string;
  informationOnContainerLiffInvoice?:string;
  externalInformationOnContainerLiffInvoice?:string;
  listLocations?:CustomerLocations[];
  listRoutes?:CustomerRoutes[];
  listNormalRoute?:CustomerNormalRoutes[];
  listTollRoutes?:CustomerTollRoutes[];
}
