export interface PotentialCustomer {
    id?: number;
    customerName?: string;
    nameEnglish?: string;
    customerCode?: string;
    provinceCode?: string;
    districtCode?: string;
    industrialZoneId?: number | null;
    address?: string;
    taxCode?: string;
    tel?: string;
    fax?: string;
    website?: string;
    countryCode?: string;
    bankAccountNumber?: string;
    bankName?: string;
    contact?: string;
    contactPosition?: string;
    contactTel?: string;
    contactEmail?: string;
    employeeId?: number | null;
    branchId?: number | null;
    parentId?: number | null;
    customerType?: number | null;
    acceptStep?: number | null;
    notes?: string;
    latitude?: number | null;
    longitude?: number | null;
    status?:boolean;
    checked?: boolean;
}
