export interface ReportViewModel {
  id?: string;
  name?: string;
  m?: string;
  n?: number | null;
  type?: string;
  shipmentId?: number | null;
  debitNoteId?: number | null;
  customerCode?: string;
  customerName?: string;
  jobId?: string;
  shipmentNo?: string;
  cdsNumber?: string;
  hawB_HBL?: string;
  mawB_MBL?: string;
  invoiceNo?: string;
  bookingNo?: string;
  loaiHinh?: string;
  referCode?: string;
  maPhi?: string;
  tenPhi?: string;
  noiDung?: string;
  contents?: string;
  ghiChu?: string;
  luongHang?: string;
  soLuong?: string;
  donViTinh?: string;
  tienTe?: string;
  trangThai?: boolean | null;
  totalAmount?: number | null;
  doanhThuVat?: number | null;
  doanhThuHaiQuan?: number | null;
  doanhThuVanTai?: number | null;
  doanhThuKhac?: number | null;
  chiPhiOps?: number | null;
  chiPhiVanTai?: number | null;
  chiPhiVanTaiNgoai?: number | null;
  chiPhiVat?: number | null;
  loiNhuan?: number | null;
  ngayDoanhThu?: string;
  ngayToKhai?: string;
  ngayHoaDon?: string;
  soHopDong?: string;
  soPhieu?: string;
  soHoaDon?: string;
  soHoaDonDelta?: string;
  debitNo?: string;
  tongTien?: number | null;
  soTien?: number | null;
  soTienUsd?: number | null;
  vatUsd?: number | null;
  tongTienUsd?: number | null;
  gw?: number;
  cbm?: number;
  cont?: number;
  pallet?: number;
  package?: number;
  dienGiai?: string;
  cdsDate?: string;
  employeeName?: string;
  employeeCode?: string;
  ngay?: string;
  paymentGroupCode?: string;
  revenueGroupCode?: string;
  vat?: number | null;
  note?: string;
  chiNhanh?: string;
  phapnhan?: string;
  debitAccount?: string;
  creditAccount?: string;
  duyet?: boolean | null;
  buoc?: number | null;
  unit?: string;
  quantity?: number;
  price?: number;
  jobDate?: string;
  exchangeRate?: number;
  currency?: string;
  doanhThuTong?: number;
  doanhThuTongVat?: number;
  chiPhiTong?: number;
  chiPhiTongVat?: number;
  refDate?: string;
  supplierName?: string;
  status?: number;
  step?: number;
  isPaymented?: boolean;
  invoiceDate?: string;
  invoicePattern?: string;
  refNo?: string;
  checked?: boolean;
  accountingDate?: string;
  isDirectPayment?: number;
}
