import { ShipmentBranch, ShipmentContSeal, ShipmentPackage } from ".";
export interface Shipment{
  id?: number;
  jobId?: string;
  customerId?: number ;
  contractId?: number ;
  jobType?: number ;
  jobDate?: string;
  cdsNumber?: string;
  cdsDate?: string;
  hawB_HBL?: string;
  mawB_MBL?: string;
  invoiceNo?: string;
  salesContract_PO?: string;
  cartons?: number ;
  weight?: number ;
  volume?: number ;
  pallets?: number ;
  containers?: number ;
  documentStaff?: string;
  cDSStaff?: string;
  handlingStaff?: string;
  jobStaff?: string;
  customerRefNo?: string;
  shipmentNo?: string;
  services?: string;
  bookingNo?: string;
  freeDemTime?: string;
  sICutoffTime?: string;
  pickupPlace?: string;
  pickupTime?: string;
  pickupContact?: string;
  deliveryPlace?: string;
  deliveryTime?: string;
  deliveryContact?: string;
  emptyContReturn?: string;
  emptyContDeadline?: string;
  cutoffTime?: string;
  lOLOInvoiceInfo?: string;
  otherInvoiceInfo?: string;
  emptyContPickupPlace?: string;
  customsInspectionReposition?: boolean ;
  importExport?: number ;
  freightTerm?: string;
  shipmentType?: number ;
  shippingType?:number;
  teamId?:number;
  notes?: string;
  branchId?: number;
  isFinish?: boolean;
  shipmentBranches?: ShipmentBranch[];
  shipmentContSeals?: ShipmentContSeal[];
  shipmentPackages?: ShipmentPackage[];
  shipmentServiceDetails?:ShipmentServiceDetail[];
  customerName?:string;
  customerCode?:string;
  status?:boolean;
  checked?: boolean;
  quotationId?:number;
  shipmentTypeName?:string;
  jobDig?:boolean;
  accept?:boolean;
  isDeb?:boolean;
  isDebApproved?:boolean;
  isDebited?:boolean;
  conts?:string;
  mergeBranchCode?:string;
  createdByName?:string;
  createdDate?:string | Date;
  createdBy?:string;
  employeeId?:number;
  //Thêm biến này đế lấy số lượng cont phân biệt theo loại cont

}

export interface ShipmentServiceDetail {
  id?: number;
  shipmentId?: number;
  feeId?: number | null;
  contents?: string;
  amount?: number | null;
  notes?: string;
  code?: string;
  serviceId?: number | null;
  serviceName?: string;
  branchId?: number | null;
  unit?: string;
  currency?: string;
  num?: number | null;
  isOk?: boolean | null;
  tempId?:number;
}
