import { Status } from './../pipes/status.pipe';
import { VehicleOilQuota } from "./danhmuc/vehicle-oil-quota.model";

export interface Vihicle {
    id?: number;
    licensePlates?: string;
    vihicleTypeId?: number;
    vihicleTypeName?:string;
    vihicleTypeBotId?:number;
    garageTypeId?:number;
    garageTypeName?:string;
    garageGroupId?:number;
    tireDiagramId?:number;
    vihicleTypeBotName?:string;
    size?: string;
    yearMade?:number;
    designedPayload?:number;
    permissiblePayload?:number; 
    note?: string;
    manufacturer?: string;
    branchId?: number;
    branchName?:string;
    managementBranchId?:number;
    managementBranchName?:string;
    employeeId?:number;
    employeeFullName?:string;
    vehicleHandoverDate?: string;
    locked?: boolean;
    originalPrice?: number;
    oilQuota?: number;
    noLoadingOilQuota?: number;
    frameNumber?: string;
    engineNumber?: string;
    vehicleInspectionDeadline?: string;
    civilLiabilityInsuranceExpirationDate?: string;
    civilLiabilityInsuranceProvider?: string;
    vehicleDamageInsuranceExpirationDate?: string;
    vehicleDamageInsuranceProvider?: string;
    bankCollateral?: boolean;
    vehicleLicenseCopyExpirationDate?: string;
    createdBy?:string;
    createdByName?:string;
    createdDate?:Date | string;
    updatedBy?:string;
    updatedByName?:string;
    updatedDate?:Date | string;
    isSell?: number;
    checked?:boolean;
    listOilQuota?:VehicleOilQuota[];
    status?:number;
    feedback?:string;
}
