import { TrainingDocumentContents } from "./training-document-contents";
import { TrainingDocumentScoresDetails } from "./training-document-scores-details";

export interface TrainingDocuments {
  id?: string;
  branchId?: number;
  customerId?: number;
  customerName?: string;
  documentCode?: string;
  rootId?: string;
  parentId?: string;
  title?: string;
  summary?: string;
  level?: number;
  groupL1Id?: number;
  groupL1Name?: string;
  groupL2Id?: number;
  groupL2Name?: string;
  status?: number;
  isOfficialVersion?: boolean;
  deleted?: boolean;
  isShortInput?: boolean;
  createdBy?: string;
  createdByName?: string;
  createdDate?: Date | string;
  lastModified?: Date | string;
  lastModifiedBy?: string;
  lastModifiedByName?: string;
  assigneeId?: string;
  assigneeName?: string;
  assignedDate?: Date | string;
  contents?: TrainingDocumentContents[];
  socreDetails?:TrainingDocumentScoresDetails[];
  checked?: boolean;
  rStatus?: string;
  steps?: number;
  step1EvaluationScore?: number;
  step2EvaluationScore?: number;
  totalScore?: number;
  parentCreatedBy?: string;
  parentCreatedByName?: string;
  rootCreatedBy?: string;
  rootCreatedByName?: string;
}
