
import { DispatchOrderEtc } from "@app/shared/models";
import { DispatchOrderFee } from "@app/shared/models/transports/dispatchorders/dispatch-order-fee";
import { ShippingTask } from "@app/shared/models/transports/shipping-task.model";
import { TransportOrderSegment } from "@app/shared/models/transports/dispatchorders/transport-order.model";

export interface DispatchOrderFcl {
    id?: number;
    refNo?: string;
    branchId?: number;
    shortWay?:boolean;
    shippingUnitId?: number;
    shippingUnitCode?: string;
    shippingUnitName?: string;
    referCode?: string;
    isSubcontractors?: boolean;
    vehicleId?: number;
    vehiclelLicensePlates?: string;
    vehicleType?: number;
    vehicleTypeCharge?: number;
    moocId?: number;
    moocLicensePlates?: string;
    driverId?: number;
    driverName?: string;
    driverTel?: string;
    secondDriverId?: number;
    secondDriverName?: string;
    secondDriverTel?: string;
    fuelDriverId?: number;
    weight?: number;
    volume?: number;
    isExport?: boolean;
    contType?: string;
    fullRoute?: string;
    oilPrice?: number;
    oilCompensation?: number;
    reasonOilCompensation?: string;
    luotdiQuabai?:boolean;
    luotveQuabai?:boolean;
    subcontractorsQuoteCode?: string;
    subcontractorsQuoteRouteCode?: string;
    subcontractorsPurchaseCost?: number;
    subcontractorsPurchaseVat?: number;
    dispatchSummarize?: string;
    inquiryTimeToTheFactory?: string;
    inquiryTimeToThePorts?: string;
    contactInformation?: string;
    note?: string;
    startVehicleOdor?: number;
    startEupOdor?: number;
    finishVehicleOdor?: number;
    finishEupOdor?: number;
    gradeSubcontractors?: number;
    evaluationSubcontractors?: string;
    gradeDriver?: number;
    evaluationDriver?: string;
    startedDate?: Date;
    finished?: boolean;
    noteFinished?: string;
    finishedDate?: Date;
    status?: number;
    isDeny?: boolean;
    feedback?:string;
    createdDate?: string;
    createdBy?: string;
    createdByName?: string;
    closingBy?: string;
    closingDate?: string;
    updatedBy?: string;
    updatedDate?: string;
    deleted?: boolean;
    isFuelApproval?: boolean;
    isRePaymentEtc?: boolean;
    isEmployeeDebitClosing?: boolean;
    shippingTaskId?: number;
    chang1IdLuotDi?: number;
    chang1KmLuotDi?: number;
    chang2IdLuotDi?: number;
    chang2KmLuotDi?: number;
    dieuchinhKmLuotDi?: number;
    lydoDieuchinhLuotdi?: string;
    luonghangIdLuotDi?: number;
    dinhmucDauLuotDi?: number;
    tongdauLuotDi?: number;
    chang1IdLuotVe?: number;
    chang1KmLuotVe?: number;
    chang2IdLuotVe?: number;
    chang2KmLuotVe?: number;
    dieuchinhKmLuotVe?: number;
    lydoDieuchinhLuotVe?: string;
    luonghangIdLuotVe?: number;
    dinhmucDauLuotVe?: number;
    tongdauLuotVe?: number;
    luonghangTrungchuyenCang?: number;
    cang1Id?: number;
    cang2Id?: number;
    kmTrungchuyenCang?: number;
    dinhmucDauTrungchuyenCang?: number;
    tongdauTrungchuyenCang?: number;
    dieuchinhKmTrungchuyenCang?: number;
    kmTrungchuyenCangSauDieuchinh?: number;
    lydoDieuchinhKmTrungchuyenCang?: string;
    luonghangTrungchuyenNhamay?: number;
    nhamay1?: number;
    nhamay2?: number;
    kmTrungchuyenNhamay?: number;
    dinhmucDauTrungchuyenNhamay?: number;
    tongdauTrungchuyenNhamay?: number;
    ghichuTrungchuyenNhamay?: string;
    luonghangLuotdiName?: string;
    chang1LuotdiName?: string;
    chang2LuotdiName?: string;
    luonghangTrungchuyenCangName?: string;
    cang1LuotdiName?: string;
    cang2LuotdiName?: string;
    luonghangTrungchuyenNhamayName?: string;
    nhamay1LuotdiName?: string;
    nhamay2LuotdiName?: string;
    luonghangTrungchuyenCangVe?: number;
    cang1IdVe?: number;
    cang2IdVe?: number;
    kmTrungchuyenCangVe?: number;
    dinhmucDauTrungchuyenCangVe?: number;
    tongdauTrungchuyenCangVe?: number;
    dieuchinhKmTrungchuyenCangVe?: number;
    kmTrungchuyenCangVeSauDieuchinh?: number;
    lydoDieuchinhKmTrungchuyenCangVe?: string;
    luonghangTrungchuyenNhamayVe?: number;
    nhamay1Ve?: number;
    nhamay2Ve?: number;
    kmTrungchuyenNhamayVe?: number;
    dinhmucDauTrungchuyenNhamayVe?: number;
    tongdauTrungchuyenNhamayVe?: number;
    ghichuTrungchuyenNhamayVe?: string;
    luonghangLuotveName?: string;
    chang1LuotveName?: string;
    chang2LuotveName?: string;
    luonghangTrungchuyenCangveName?: string;
    cang1LuotveName?: string;
    cang2LuotveName?: string;
    luonghangTrungchuyenNhamayveName?: string;
    nhamay1LuotveName?: string;
    nhamay2LuotveName?: string;
    kmLuotdi?: number;
    kmLuotve?: number;
    tongKm?:number;
    tongdau?: number;
    chiphidau?: number;
    isSummarized?: boolean;
    accountingDate?: string;
    shippingTaskItem?: ShippingTask;
    listEtc?: DispatchOrderEtc[];
    listFee?: DispatchOrderFee[];
    listDetailed?:DispatchOrderFclDetail[];
    checked?:boolean;
    rStatus?:string;
    containerNumbers?: string;
    locations?: string;
    containerList?: string[];
    locationList?: string[];
    hawB_HBL?: string;
    mawB_MBL?: string;
    bookingNo?: string;

    // ===== TO refactor (2026-05-15) =====
    // isLegacy=1: lệnh cũ (pre-refactor), modal v1.
    // isLegacy=0: lệnh mới, modal v2 — có route segments + map Vietmap, không có Chang/Luonghang/Cang/Nhamay.
    isLegacy?: boolean;
    // RefNo của TO link (server set sau khi CreateWithTO). Chỉ output.
    toRefNo?: string;
    // Segments của TO (truyền vào createWithTo/updateWithTo; nhận từ getDetailWithTo).
    segments?: TransportOrderSegment[];
}

export interface DispatchOrderFclDetail {
    id?: number;
    refNo?: string;
    shippingTaskId?: number;
    shippingTaskItem?:ShippingTask;
}
