export interface SalesCustomer {
  customerId?: number;
  customerCode?: string;
  customerName?: string;
  nameE?: string;
  nameAbbreviation?: string;
  address?: string;
  tel?: string;
  contact?: string;
  contactTel?: string;
  contactPosition?: string;
  email?: string;
  fax?: string;
  website?: string;
  taxCode?: string;
  account?: string;
  bank?: string;
  salesId?: number | null;
  salesFullName?:string;
  managerSalesId?: number | null;
  managerSalesFullName?:string;
  branchId?: number | null;
  branchCode?:string;
  branhcName?:string;
  provinceCode?: number | null;
  industrialZonesId?: number | null;
  countryCode?: number | null;
  scopeofOperationId?: number | null;
  customerType?: number | null;
  debtlimit?: number;
  lock?: boolean;
  notes?: string;
  symbol?: string;
  accept?: boolean;
  ok?: boolean;
  createdBy?: string;
  createdByName?:string;
  createdDate?: Date | string;
  checked?:boolean;
  dk05Code?:string;
  quotationId?:number;
}
