export interface DispatchOrderExport {
  refNo?: string;
  shippingUnitCode?: string;
  shippingUnitName?: string;
  isSubcontractors?: boolean;
  vihiclelLicensePlates?: string;
  vihicleType?: number;
  moocLicensePlates?: string;
  driverName?: string;
  driverTel?: string;
  secondDriverName?: string;
  secondDriverTel?: string;
  fuelDriverNae?:string;
  numberOfVihicle?: number;
  numberOfPackage?: number;
  weight?: number;
  volume?: number;
  numberOfPallet?: number;
  numberOfCont?: number;
  contType?: string;
  fullRoute?: string;
  oilQuota?: number;
  oilPrice?: number;
  quotaAdjusted?: number;
  quotaAdjustedReason?: string;
  subcontractorsQuoteCode?: string;
  subcontractorsQuoteRouteCode?: string;
  dispatchSummarize?: string;
  inquiryTimeToTheFactory?: Date | string;
  inquiryTimeToThePorts?: Date | string;
  contactInformation?: string;
  note?: string;
  kmQuota?: number;
  startVehicleOdor?: number;
  finishVehicleOdor?: number;
  locked?: boolean;
  finished?: boolean;
  noteFinished?:string;
  rStatus?:string;
  createdByName?:string;
}
