import { DbsDocuments } from "./dbs-documents.model";
import { DbsExtraReference } from "./dbs-extra-reference.model";
import { DbsShipmentActions } from "./dbs-shipment-actions.model";
import { DbsShipmentListAttachFiles } from "./dbs-shipment-list-attach-files.model";
import { DbsShipmentWorkflow } from "./dbs-shipment-workflow.model";
import { DbsShippingUnit } from "./dbs-shipping-unit.model";

export interface DbsShipment {
  id?: number;
  ediCustomerNumber?: string;
  ediCustomerDepartment?: string;
  ediReference?: string;
  internalShipmentNumber?: string;
  dateTimeZone?: Date | string | null;
  primaryReference?: string;
  serviceLevel?: string;
  tariffType?: string;
  servicesName?: string;
  originPlaceCode?: string;
  destinationPlaceCode?: string;
  quantity?: number;
  packageCode?: string;
  grossWeight?: number;
  netWeight?: number;
  pickupNameLine1?: string;
  pickupAddressLine1?: string;
  pickupAddressLine2?: string;
  pickupCityName?: string;
  deliveryNameLine1?: string;
  deliveryAddressLine1?: string;
  deliveryAddressLine2?: string;
  deliveryCityName?: string;
  notes?: string;
  createdBy?: string;
  createdByName?:String;
  createdDate?: Date | string;
  status?: number;
  rStatus?:string;
  acceptBy?: string;
  acceptByName?:string;
  acceptDate?: Date | string;
  sendDocBy?: string;
  sendDocByName?:string;
  sendDocDate?: Date | string;
  updatedBy?: string;
  updatedDate?: Date | string;
  branchId?: number;
  checked?:boolean;
  shippingUnits?: DbsShippingUnit[];
  extraReferences?: DbsExtraReference[];
  documents?: DbsDocuments[];
  shipmentListAttachFiles?: DbsShipmentListAttachFiles[];
  shipmentListWorkflows?:DbsShipmentWorkflow[];
  shipmentActions?:DbsShipmentActions[];
}
