export interface WorkflowReportBc01 {
  totalRows?: number;
  cnQuanlyKH?: string;
  makh?: string;
  tenKh?: string;
  cnTaoviec?: string;
  jobId?: string;
  idCv?: number;
  tenCongviec?: string;
  nguoitao?: string;
  ngaytao?: Date | string;
  cnThuchien?: string;
  tenNhomthuchien?: string;
  nguoiNhanviec?: string;
  nguoiThuchien?: string;
  estimatedStartTime?: Date | string;
  estimatedFinishTime?: Date | string;
  opManChangedEstimatedStartTime?: Date | string;
  opManChangedEstimatedFinishTime?: Date | string;
  opManUpdateNotes?: string;
  opManGradeByCS?: number;
  opManEvaluationByCS?: string;
  opGradeByCS?: number;
  opEvaluationByCS?: string;
  opManGradeByOp?: number;
  opManEvaluationByOp?: string;
  csGradeByOp?: number;
  csEvaluationByOp?: string;
  opGradeByOpMan?: number;
  opEvaluationByOpMan?: string;
  csGradeByOpMan?: number;
  csEvaluationByOpMan?: string;
  isJobFinish?: boolean;
  jobFinishTime?: Date | string;
}
