import { Shipment } from "../shipment.model";
import { WorkflowAttackFiles } from "./workflow-attack-files.model";
import { WorkflowContSeal } from "./workflow-cont-seal.model";
import { WorkflowJobOption } from "./workflow_joboption.model";
import { WorkflowJobOptionProcedure } from "./workflow_joboption_procedure.model";

export interface  Workflow {
    checked?:boolean;
    id?: number;
    branchId?: number;
    customerId?: number;
    customerCode?:string;
    customerName?: string;
    referCode?: string;
    jobId?: string;
    shipmentId?:number;
    jobName?:String;
    estimatedStartTime?: Date | string;
    estimatedFinishTime?: Date | string;
    jobToughness?: number;
    jobToughnessName?:string;
    handlingGroupId?: number;
    listHandlingGroupId?:number[];
    handlingGroupName?:string;
    jobGroupId?: number;
    jobGroupName?:string;
    jobDescription?: string;
    jobReceivingUserId?: string;
    jobReceivingUserFullName?:string;
    jobReceivingTime?: Date | string;
    jobAssigningUserId?: string;
    jobAssigningUserFullName?:string;
    joaAssigningTime?: Date | string;
    jobAssignedUserId?: string;
    jobAssignedUserFullName?:string;
    isMainJob?: boolean;
    mainJobId?:number;
    opManChangedEstimatedStartTime?: Date | string;
    opManChangedEstimatedFinishTime?: Date | string;
    opManUpdateNotes?: string;
    opManGradeByCS?: number;
    opManEvaluationByCS?: string;
    opGradeByCS?: number;
    opEvaluationByCS?: string;
    opManGradeByOp?: number;
    opManEvaluationByOp?: string;
    csGradeByOp?: number;
    csEvaluationByOp?: string;
    opGradeByOpMan?: number;
    opEvaluationByOpMan?: string;
    csGradeByOpMan?: number;
    csEvaluationByOpMan?: string;
    deliveryTimeId?: number;
    deliveryTimeDescription?:string;
    loadingUnloadingTypeId?: number;
    loadingUnloadingTypeDescription?:String;
    isJobFinish?: boolean;
    jobFinishTime?: Date | string;
    noteFinish?: string;
    isJobDone?: boolean;
    jobDoneTime?: Date | string;
    noteDone?: string;
    numberOfPackage?: number;
    weight?: number;
    volume?: number;
    numberOfPallet?: number;
    numberOfCont?: number;
    contType?: number;
    typeOfServices?: string;
    placeOfLoading?:string;
    placeOfDelivery?: string;
    closingTime?: string;
    inquiryTimeToTheFactory?: string;
    inquiryTimeToThePorts?: string;
    status?: number;
    rStatus?:string;
    pickupTime?: string;
    deliveryTime?: string;
    pickupLocationId?: number;
    deliveryLocationId?: number;
    pickupLocation?: string;
    deliveryLocation?: string;
    createdDate?: Date | string;
    createdBy?: string;
    createdByFullName?:string;
    createdByTel?:string;
    updatedDate?: Date | string;
    updatedBy?: string;
    updatedByFullName?:string;
    deleted?:boolean;
    item?:Shipment;
    workflowJobOptions?: WorkflowJobOption[];
    workflowJobOptionProcedures?: WorkflowJobOptionProcedure[];
    listWorkflowAttackFiles?:WorkflowAttackFiles[];
    listWorkflowImages?:WorkflowAttackFiles[];
    listWorkflowPod?:WorkflowAttackFiles[];
    workflowContSeals?:WorkflowContSeal[];
    isAssign?:boolean;
    isBoolValue?: boolean;
    isLeader?:boolean;
    numberDuplicate?: number;
    gradeType?: string;
    grade1?: number;
    evaluation1?: string;
    grade2?: number;
    evaluation2?: string;
    refNo?:string;
    jobLocked?:boolean;
    contNo?:string;
    driverName?:string;
    driverTel?:string;
    vihiclelLicensePlates?:string;
    totalRows?:number;
    isCanon?:boolean;
}
