export interface ExternalOilPurchased {
    id?: number;
    refNo?: string;
    branchId?: number;
    branchCode?:string;
    branchName?:string;
    refDate?: Date | string;
    employeeId?: number;
    employeeFullName?:string;
    vihicleId?: number;
    licensePlates?:string;
    taxNumber?: string;
    quantity?: number;
    unitPrice?: number;
    amount?: number;
    vat?: number;
    amountAfterVat?: number;
    invoiceNo?: string;
    invoiceDate?:string;
    invoicePattern?:string;
    web?: string;
    code?: string;
    status?: number;
    createdBy?:string;
    createdByName?:string;
    createdDate?:string;
    acceptedBy?: string | null;
    acceptedDate?:string;
    acceptedByName?:string;
    feedback?: string;
    closingBy?:string | null;
    closingDate?:string;
    checked?:boolean;
    notes?:string;
    rStatus?:string;
    isCbt?:boolean;
    refNoCbt?:string;
    isCompleted?: boolean;
    supplierId?: number;
    supplierName?: string;
    isRefNoClosing?: boolean;
    cbtStatus?: number;
}
